/* Doom sound effects on the on-board piezo buzzer (PA0), plus a fan "whoosh"
 * (part-cooling fan PE11) whenever a door opens or closes.
 *
 * The steppers play the music; the buzzer adds short tones/sweeps per game
 * event. The square wave is generated by a DDS in fx_tick() at the 40 kHz
 * SysTick rate, with an optional linear pitch sweep per effect. */

#include "stm32f4xx.h"
#include "../gpio.h"
#include "sounds.h"

#define BUZ_PORT GPIOA
#define BUZ_PIN  0
#define FAN_PORT GPIOE
#define FAN_PIN  11
#define SR 40000           /* SysTick rate */

static volatile int32_t bz_freq_q8, bz_step_q8;  /* current pitch + per-tick delta (Hz<<8) */
static volatile int     bz_left;                 /* ticks of tone remaining */
static uint32_t bz_phase;
static int      bz_state;
static volatile int fan_left;                    /* ticks of fan pulse remaining */

void fx_init(void) {
    gpio_config(BUZ_PORT, BUZ_PIN, GPIO_OUT, GPIO_PP, GPIO_SPD_HIGH, GPIO_NOPULL, 0);
    gpio_clear(BUZ_PORT, BUZ_PIN);
    gpio_config(FAN_PORT, FAN_PIN, GPIO_OUT, GPIO_PP, GPIO_SPD_LOW, GPIO_NOPULL, 0);
    gpio_clear(FAN_PORT, FAN_PIN);
}

/* Play a tone sweeping from f0 to f1 Hz over ms milliseconds. */
static void buzz(int f0, int f1, int ms) {
    int ticks = ms * (SR / 1000);
    if (ticks < 1) ticks = 1;
    bz_left = 0;                            /* halt any current tone first */
    bz_phase = 0;
    bz_freq_q8 = (int32_t)f0 << 8;
    bz_step_q8 = (((int32_t)(f1 - f0)) << 8) / ticks;
    bz_left = ticks;                        /* arm last so fx_tick won't run mid-update */
}

void fx_sound(int id) {
    int fan = 0;
    switch (id) {
        case sfx_pistol:                         buzz(1500, 500, 35);  break;
        case sfx_shotgn: case sfx_sgcock:        buzz(1000, 250, 60);  break;
        case sfx_dshtgn: case sfx_dbopn:
        case sfx_dbcls:  case sfx_dbload:        buzz(800, 180, 80);   break;
        case sfx_plasma:                         buzz(1900, 1400, 25); break;
        case sfx_bfg:                            buzz(400, 1700, 140); break;
        case sfx_rlaunc:                         buzz(700, 300, 60);   break;
        case sfx_firsht:                         buzz(1200, 900, 40);  break;
        case sfx_rxplod: case sfx_firxpl:        buzz(260, 70, 180);   break;
        case sfx_sawup:  case sfx_sawful:
        case sfx_sawhit:                         buzz(320, 300, 40);   break;
        case sfx_doropn:                         buzz(200, 520, 200); fan = 1; break;
        case sfx_dorcls:                         buzz(520, 200, 200); fan = 1; break;
        case sfx_bdopn:                          buzz(220, 560, 170); fan = 1; break;
        case sfx_bdcls:                          buzz(560, 220, 170); fan = 1; break;
        case sfx_swtchn: case sfx_swtchx:        buzz(950, 950, 30);   break;
        case sfx_pstart: case sfx_pstop:         buzz(300, 300, 45);   break;
        case sfx_itemup:                         buzz(800, 1400, 60);  break;
        case sfx_wpnup:                          buzz(500, 1200, 110); break;
        case sfx_oof: case sfx_plpain:           buzz(180, 140, 110);  break;
        case sfx_telept:                         buzz(400, 1700, 160); break;
        /* very frequent / ambient — stay silent to avoid constant buzzing */
        case sfx_stnmov: case sfx_sawidl:
        case sfx_posact: case sfx_bgact:
        case sfx_dmact:  case sfx_bspact:
        case sfx_bspwlk:                         break;
        default:
            if (id >= sfx_posit1 && id <= sfx_pesit)       buzz(140, 100, 150); /* sight  */
            else if (id >= sfx_sklatk && id <= sfx_skeswg) buzz(600, 400, 55);  /* attack */
            else if (id >= sfx_pldeth && id <= sfx_skedth) buzz(320, 90, 200);  /* death  */
            else if (id >= sfx_dmpain && id <= sfx_pepain) buzz(220, 180, 90);  /* pain   */
            else                                           buzz(700, 600, 30);  /* generic*/
            break;
    }
    if (fan) {
        fan_left = 1500 * (SR / 1000);     /* ~1.5 s whoosh */
        gpio_set(FAN_PORT, FAN_PIN);
    }
}

void fx_tick(void) {
    if (bz_left > 0) {
        bz_freq_q8 += bz_step_q8;
        int f = bz_freq_q8 >> 8;
        if (f < 20) f = 20;
        bz_phase += (uint32_t)(2 * f);     /* toggle at 2f -> square wave at f */
        if (bz_phase >= SR) {
            bz_phase -= SR;
            bz_state ^= 1;
            if (bz_state) gpio_set(BUZ_PORT, BUZ_PIN);
            else          gpio_clear(BUZ_PORT, BUZ_PIN);
        }
        if (--bz_left == 0) {
            gpio_clear(BUZ_PORT, BUZ_PIN);
            bz_state = 0;
        }
    }
    if (fan_left > 0) {
        if (--fan_left == 0) {
            gpio_clear(FAN_PORT, FAN_PIN);
        }
    }
}
